# Generated by Django 3.0.5 on 2020-05-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
