# Generated by Django 3.0.5 on 2020-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
