# Generated by Django 3.0.5 on 2020-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
