# Generated by Django 3.0.5 on 2020-05-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0008_auto_20200519_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=' ', max_length=200, null=True),
        ),
    ]
