# Generated by Django 3.0.5 on 2020-06-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0013_dialog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
