# Generated by Django 3.0.5 on 2020-06-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0016_auto_20200608_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
