# Generated by Django 3.0.5 on 2020-06-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0018_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
