# Generated by Django 3.0.5 on 2020-06-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0020_chatmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('timestamp',)},
        ),
    ]
