# Generated by Django 3.0.5 on 2020-06-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0022_auto_20200614_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
