# Generated by Django 3.0.5 on 2020-06-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0023_auto_20200614_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('timestamp',)},
        ),
    ]
