# Generated by Django 3.0.5 on 2020-06-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0024_auto_20200614_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('timestamp',)},
        ),
    ]
