# Generated by Django 3.0.5 on 2020-06-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0025_auto_20200614_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
