# Generated by Django 3.0.5 on 2020-06-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0026_auto_20200614_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='updated',
        ),
    ]
