# Generated by Django 3.0.7 on 2020-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0028_auto_20200721_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(default='lightprof.css', max_length=200),
        ),
    ]
