# Generated by Django 3.0.7 on 2020-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0029_auto_20200725_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
