# Generated by Django 3.0.7 on 2020-07-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0030_auto_20200725_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(default='lightprof.css', max_length=200),
        ),
    ]
