# Generated by Django 3.0.7 on 2020-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0031_auto_20200731_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(blank=True, default='lightprof.css', max_length=200),
        ),
    ]
