# Generated by Django 3.0.7 on 2020-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0032_auto_20200731_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
