# Generated by Django 3.0.7 on 2020-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0033_auto_20200731_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
