# Generated by Django 3.0.7 on 2020-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0035_auto_20200802_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
